# Site settings
title:          Metody Sztucznej Inteligencji
#description:    "Minimal Jekyll theme for storytellers"
#baseurl:        "/tale"
url:            "https://metsi.github.io"

# Author
author:
  name:         Paweł Ksieniewicz
  url:          https://kssk.pwr.edu.pl/ksieniewicz
  email:        pawel.ksieniewicz@pwr.edu.pl@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:title
paginate:       10
